splash = false
preload = ~/Pictures/Backgrounds/nix-wallpaper-binary-black.png
preload = ~/Pictures/Backgrounds/nix-wallpaper-nineish-dark-gray.png
preload = ~/Pictures/Backgrounds/nix-wallpaper-stripes-logo.png
wallpaper = ,~/Pictures/Backgrounds/nix-wallpaper-binary-black.png